# Generated by Django 6.0.5 on 2026-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(max_length=20)),
                ('type_line', models.CharField(max_length=100)),
                ('oracle_text', models.TextField()),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('color_identity', models.JSONField(blank=True, default=list)),
                ('commander_legality', models.BooleanField(default=False)),
            ],
        ),
    ]
