# Generated by Django 6.0.5 on 2026-05-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='commander_legality',
            new_name='commander_legal',
        ),
        migrations.RemoveField(
            model_name='card',
            name='power',
        ),
        migrations.RemoveField(
            model_name='card',
            name='toughness',
        ),
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='legalities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='card',
            name='oracle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='prices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='released_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='oracle_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
